name: CI

on: push

jobs:
  unit-tests:
    name: Check all tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Launch premake5
        run: |
          premake5 gmake2
          make
      - name: Launch tests
        run: premake5 tests
      
