name: CI

on: push

jobs:
  unit-tests:
    name: Check all tests
    runs-on: ubuntu-latest
  
    steps:
      - name: Install Premake 5
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xzf premake-5.0.0-beta2-linux.tar.gz
          sudo mv premake5 /usr/local/bin
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Launch premake5
        run: |
          premake5 gmake2
          make
      - name: Launch tests
        run: ./ChessEngine/bin/Debug/ChessEngine/ChessEngineTest
        

      
