name: CI

on: push

jobs:
  unit-tests:
    name: Check all tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Launch premake5
        run: |
          premake5 gmake2
          make
      - name: Launch tests
        run: premake5 tests

      
