name: CI

on: push

jobs:
  unit-tests:
    name: Check all tests
    runs-on: ubuntu-latest
  
    steps:
      - name: Clone repo
        run: git clone --recursive git@github.com:Gistred/AutoChess.git
      - name: Launch premake5
        run: |
          premake5 gmake2
          make
      - name: Launch tests
        run: premake5 tests
      
